In [6]:
import numpy as np

In [13]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[1, 2 ,3 ,4 ,5], [6 ,7 ,8, 9 ,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# getting dimesions 
a.ndim

1

In [6]:
b.ndim

2

In [9]:
# getting shape
a.shape

(3,)

In [10]:
b.shape

(2, 5)

In [14]:
# getting datatype
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('int64')

In [15]:
# getting size
a.itemsize

4

In [16]:
b.itemsize

8

In [17]:
a.nbytes

12

In [18]:
b.nbytes

80

# Accesing and Changing specific elements, rows, columns, etc...

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


**getting specific element**

In [20]:
# syntax a[row, col]
# row and col indexing starts from 0
a[1, 5]

np.int64(13)

**getting a specific row**

In [21]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

**getting a speific column**

In [22]:
a[:, 2]

array([ 3, 10])

**getting a little bit fancy**

In [23]:
# syntax a[rowind, starind : endind : step]
a[0, 1 : 6 : 2]

array([2, 4, 6])

**changing elements**

In [24]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
# changing a col with same value i.e., 5
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [27]:
#changing col with different values
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**3D example**

In [28]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# [works outside in]
b[0, 1, 1]

np.int64(4)

In [30]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

**replacing elements**

In [31]:
b[:, 1, :] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initialising different types of arrays

In [33]:
# all zeroes
a = np.zeros(2)
print(a)

[0. 0.]


In [34]:
a = np.zeros((2, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# all ones
b = np.ones((2, 3, 2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [36]:
# initialising array with any number (shape, number)
np.full((2, 3), 999)

array([[999, 999, 999],
       [999, 999, 999]])

In [39]:
# full_like(arr, number)
np.full_like(a, 100)

array([[100., 100., 100.],
       [100., 100., 100.]])

In [40]:
# initialising with random values
np.random.rand(2, 3)

array([[0.65158111, 0.23828975, 0.4789814 ],
       [0.19788341, 0.79289648, 0.17715607]])

In [41]:
#                (upper lim, size = (shape))
#lower lim is 0 by default
np.random.randint(10, size = (3, 3))

array([[3, 1, 0],
       [6, 8, 2],
       [3, 8, 7]], dtype=int32)

In [43]:
# THE IDENTITY MATRIX
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# repeating an array
arr = np.array([1, 2, 3])
np.repeat(arr, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [49]:
arr2 = np.array([[4, 5, 6]])
np.repeat(arr2, 4, axis= 0)

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [59]:
# print this
# [[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 9. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]]


t = np.ones((5, 5))
z = np.zeros((3, 3))
z[1, 1] = 9
t[1 : 4, 1 : 4] = z
print(t)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


***be careful while copying arrays***

In [7]:
a = np.array([1, 2, 3])
b = a
print(b)
b[0] = 100
print(b)
print(a) # a also gets changed, this is the problem

[1 2 3]
[100   2   3]
[100   2   3]


In [8]:
## solution
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)


[100   2   3]
[1 2 3]


# Mathematics

In [9]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [10]:
a + 2

array([3, 4, 5, 6])

In [11]:
a - 1

array([0, 1, 2, 3])

In [12]:
a * 2

array([2, 4, 6, 8])

In [13]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [14]:
a ** 2

array([ 1,  4,  9, 16])

In [15]:
b = np.array([1 ,0, 1 ,0])
a + b

array([2, 2, 4, 4])

In [16]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra


In [17]:
# multiplication
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print(b)
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [18]:
# determinant 
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Statistics


In [19]:
stats = np.array([[1, 2, 3], [4 ,5 ,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.min(stats, axis = 0) #rowwise

array([1, 2, 3])

In [21]:
np.min(stats, axis = 1) #columnwise

array([1, 4])

In [22]:
np.min(stats)

np.int64(1)

In [23]:
np.max(stats)

np.int64(6)

In [24]:
np.sum(stats)

np.int64(21)

## Reorganising Arrays

In [28]:
before = np.array([[1, 2, 3, 4], [5 ,6 ,7 ,8]])
print(before)

## RESHAPING is valid till the number of elemets is same 

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [31]:
## vertically stacking Vectors

v1 = np.array([1, 2 ,3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [33]:
np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [35]:
## HOrizontal Stack

h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous


## Load data from file

In [45]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

### Boolean Masking and Advanced Indexing

In [42]:
filedata  > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [43]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [47]:
## INDEXING WITH A LIST IN NUMPY
a = np.array([1, 3, 5 ,6])
a[[1, 3]]

array([3, 6])